export const Songs = [
  {
    id: 0,
    name: "a1",
    title: "हज़ार बार सुनलो फिर भी दिल नहीं भरेगा ",
    author: "Shri Ram Bhakti",
    img1: "../Images/Image/ramji1.jpg",
    img2: "../Images/Image/hanuman1.jpg",
    img3: "../Images/Image/ramji2.jpg",
    img4: "../Images/Image/hanuman2.jpg",
  },
  {
    id: 1,
    name: "a2",
    title: "नींद में भी गाओगे इतना मधुर है ये भजन ",
    author: "Shri Ram Bhakti",
    img1: "../Images/Image/krishan1.jpg",
    img2: "../Images/Image/krishan2.jpg",
    img3: "../Images/Image/krishan3.jpg",
    img4: "../Images/Image/krishan4.jpg",
  },
  {
    id: 2,
    name: "a3",
    title: "JINKI PRATIMA",
    author: "Pamela Jain",
    img1: "../Images/Image/krishan1.jpg",
    img2: "../Images/Image/krishan2.jpg",
    img3: "../Images/Image/krishan3.jpg",
    img4: "../Images/Image/krishan4.jpg",
  },
  {
    id: 3,
    name: "a4",
    title: "संध्या भक्ति - सावन सोमवार स्पेशल ",
    author: "Sandhya Bhakti",
    img1: "../Images/Image/mahadev1.jpg",
    img2: "../Images/Image/mahadev2.jpg",
    img3: "../Images/Image/mahadev3.jpg",
    img4: "../Images/Image/mahadev4.jpg",
  },
  {
    id: 4,
    name: "a7",
    title: "शिव के चरणों में करके बसेरा",
    author: "Bhajan India",
    img1: "../Images/Image/mahadev1.jpg",
    img2: "../Images/Image/mahadev2.jpg",
    img3: "../Images/Image/mahadev3.jpg",
    img4: "../Images/Image/mahadev4.jpg",
  },
  {
    id: 5,
    name: "a8",
    title: "Hamare Sath Shri Raghunath to kis bat ki chinta",
    author: "Karm Shri India",
    img1: "../Images/Image/ramji3.jpg",
    img2: "../Images/Image/hamuman2.jpg",
    img3: "../Images/Image/ramji4.jpg",
    img4: "../Images/Image/hanuman4.jpg",
  },
  {
    id: 6,
    name: "a9",
    title: "Koi Hanuman Jaisa Nahi",
    author: "Bhajan India",
    img1: "../Images/Image/ramji1.jpg",
    img2: "../Images/Image/ramji2.jpg",
    img3: "../Images/Image/ramji3.jpg",
    img4: "../Images/Image/ramji4.jpg",
  },
  {
    id: 7,
    name: "a10",
    title: "नाम है तेरा तारण हारा |",
    author: "Bhajan India",
    img1: "../Images/Image/krishan1.jpg",
    img2: "../Images/Image/krishan2.jpg",
    img3: "../Images/Image/krishan3.jpg",
    img4: "../Images/Image/krishan4.jpg",
  },
];

export default Songs;
